project:
  type: website
  output-dir: docs


website:
  title: "Thomas W. Kupferer, Jr.<br>PQHS 431- Lab 7 - Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: posts/
        text: Blog
        

format:
  html:
    theme: superhero
    css: styles.css
    toc: true


editor: visual

